# ==========================================================
# PART 1: Core Utility Functions for Finite Field Extensions
# ==========================================================

def ext_inv(Fl, Fs, mat):
    """
    Maps a coordinate matrix over the subfield Fs back to a vector over the extension field Fl.
    Used for reconstructing Fqm elements from their Fq-linear components.
    """
    m = Fl.degree() // Fs.degree()
    # Use the basis of the extension field relative to the subfield
    base_ext = [Fl.gen()^i for i in range(m)]
    
    output_list = []
    for j in range(mat.ncols()):
        # Linear combination: sum(coefficient * basis_element)
        el = sum(mat[i, j] * base_ext[i] for i in range(m))
        output_list.append(el)
    return vector(Fl, output_list)

def rand_vec(Fl, Fs, rk, leng):
    """
    Generates a random vector of length 'leng' over Fl with a specific rank 'rk' over Fs.
    """
    u = Fl.degree() // Fs.degree()
    A_mat = matrix.random(Fs, u, rk)
    while A_mat.rank() != rk:
        A_mat = matrix.random(Fs, u, rk)
    B_mat = matrix.random(Fs, rk, leng)
    while B_mat.rank() != rk:
        B_mat = matrix.random(Fs, rk, leng)
        
    return ext_inv(Fl, Fs, A_mat * B_mat)

def construction_Diag(M0, n):
    """
    Constructs a block diagonal transition matrix repeating M0 n times.
    """
    return block_diagonal_matrix([M0] * n, subdivide=False)

def diagonal_matrix_rank(F, lam, n=None):
    """
    Generates a diagonal matrix of rank lam over the field F = GF(q^m)

    INPUT:
        - F   : finite field GF(q^m)
        - lam : desired rank (integer)
        - n   : matrix size (optional, default = lam)

    OUTPUT:
        - Diagonal matrix D of size n x n and rank lam
    """

    if n is None:
        n = lam

    if lam > n:
        raise ValueError("The rank lam must be <= n")

    # Generate lam non-zero elements
    diag_entries = []
    while len(diag_entries) < lam:
        x = F.random_element()
        if x != 0:
            diag_entries.append(x)

    # Complete with zeros (using existing logic)
    for ii in range(n-lam) :
        el = 0#GF(2).random_element()
        dd = diag_entries[el]
        #Dia = Dia + [dd]
        diag_entries = diag_entries+[dd]

    # Build the diagonal matrix
    D = diagonal_matrix(F, diag_entries)

    return D, diag_entries


def devectorisation(v, n, s):
    """
    Reshapes a flat coordinate vector 'v' of length n*s into an (s x n) matrix.
    Each column represents one element of the extension field.
    """
    V = vector(v)
    # Populate an n x s matrix and transpose to get s x n
    M = matrix(V.base_ring(), n, s, V.list())
    return M.transpose()

def etandu_dun_vecteur(c):
    """
    Constructs the q-ary image by manually converting Fqm elements to 
    polynomials over Fq before coordinate extraction.
    """
    # 1. Access the relative vector space
    # map=True gives us a 'to_V' function that is generally safer
    V, from_V, to_V = Fqm.vector_space(Fq_global, map=True)
    
    flat_list = []
    for x in c:
        # 2. Convert x to an element of the vector space V
        # to_V(x) handles the algebraic decomposition over Fq_global
        v_coords = to_V(x)
        
        # 3. Extend the flat list with the coordinates (already in Fq_global)
        flat_list.extend(list(v_coords))
        
    return vector(Fq_global, flat_list)

def etandu_B(B, v):
    """
    Constructs the concatenated G_s of (bi * v) where v is a fixed vector).
    """
    G_tb = matrix(B[0] * v)
    
    for i in range(1, len(B)):
        G_tb = G_tb.stack(matrix(B[i] * v))
        
    return G_tb


def superposition(B, G_t):
    """
    Extends each row of the target matrix H_t through the basis B (b_i g_j).
    """
    G_s = etandu_B(B, G_t[0])
    
    for j in range(1, G_t.nrows()):
        G_s = G_s.stack(etandu_B(B, G_t[j]))
        
    return G_s

def _Expand(G_s):
    """
    Expands a generator matrix row by row.
    Fixed to explicitly set the base ring to Fq_global.
    """
    rows = [etandu_dun_vecteur(row) for row in G_s.rows()]
    # Ensure the matrix is explicitly defined over the Fq subfield
    return matrix(Fq_global, rows)


def phiBvec(G, m, n, k_prime, Diag):
    "Cette fonction construit l'image q-aire vectoriel du sous code."
    "G^vec est construit en suivant la Remark 2.3 qui dit que l'image q-aire du code est generated by"
    "{ phiBvec(b_i g_j) | 1 ⩽ i ⩽ m, 1 ⩽ j ⩽ k }."
    "G est la matrice génératrice du code de depart et k_prime la dimension du sous code"
    "Diag is the transistion matrice de la base cononique à une base quelconque"
    G_s = superposition(base, G)
    Gext = _Expand(G_s)
    # Basis Transformation & Transition Matrices ---
    # Apply the transition matrix to the extended generator matrix
    IQG_B_i = Gext * Diag
    return IQG_B_i


    
# ==========================================================
# PART 2: Cryptosystem Parameters & Field Hierarchy Setup
# ==========================================================
    """
    Supports multi-field expansion (q=2^s) via relative 
    algebraic embeddings.
    """

p = 2
s_exp = 1
q = p**s_exp
Fq_global = GF(q, names=('z',)); (z,) = Fq_global._first_ngens(1)

n = 34
m = n 
k = 24
k_prime = 800 
delta = 1

# Construction of finite field
Fqm = Fq_global.extension(m, name='a')
(a,) = Fqm._first_ngens(1)

VV = VectorSpace(Fqm, n)
base = [a^i for i in range(m)]

# ==========================================================
# PART 3: Code Construction and Decoding Execution
# ==========================================================

# 1. Generate Gabidulin Code and apply the diagonal transformation to obtain a generator matrix G of a lambda-Gabidulin code
C1 = codes.GabidulinCode(Fqm, n, k, Fq_global)
G1 = C1.generator_matrix()
D, _ = diagonal_matrix_rank(Fqm, delta, n)
G = G1 * D

# 2. Setup Basis Transformation Matrices
M0 = random_matrix(Fq_global, m, m,algorithm='echelonizable', rank=m)
Diag = construction_Diag(M0, n)
Diag2 = construction_Diag(M0^-1, n)

# 3. Compute the q-ary image of the subcode
IQG_B_i = phiBvec(G, m, n, k_prime, Diag)
P = random_matrix(Fq_global, k_prime, k * m)
while P.rank() != k_prime:
    P = random_matrix(Fq_global, k_prime, k * m)

G_sc = P * IQG_B_i
H_sc = LinearCode(G_sc).parity_check_matrix()

# 4. Encryption (Syndrome computation)
e = rand_vec(Fqm, Fq_global, 2, n)
e_expanded = etandu_dun_vecteur(e)
syndrome = H_sc * e_expanded

# 5. Decryption
# Solve for a vector y sharing the same syndrome
y = H_sc.solve_right(syndrome)


# Construction of y_prime the Fqm associated vector of y
y_coords = y * Diag2 # Transform coordinates back to the canonical basis
y_matrix = devectorisation(y_coords, n, m)
y_prime = vector(Fqm, [sum(y_matrix[i, j] * base[i] for i in range(m)) for j in range(n)])

# Final Rank-Metric Decoding
ww = VV(y_prime * D^(-1))
try:
    decoded_codeword = C1.decode_to_code(ww)
    print("Lambda-Gabidulin decoding successful!")
    
    # Validation: Compare recovered error to original
    recovered_error = etandu_dun_vecteur((decoded_codeword - ww) * D) * Diag
    print("Verification (Success == True):", recovered_error == e_expanded)
    print("recovered_error:", recovered_error)
except Exception as err:
    print(f"Decoding failed: {err}")
